### ISSUE TITLE
Refactor away from relying on `this` in module scope.

### ISSUE THREAD

**Issue by rwjblue** [ebryn/backburner.js#128]
References to `this` in root module scope are no longer guaranteed to be `window`, and some transpilers actively rewrite `this` to `undefined` to ensure future compatibility.

Example with Esperanto:

Input (as used [here](https://github.com/ebryn/backburner.js/blob/dab096ce8d7025aa82353c00aa4b5e38f56152e2/lib/backburner.js#L20)):

```javascript
var global = this;
``` 

Output:

```javascript
define(function () {

	'use strict';

	var global = undefined;

});
```

Replacing `this` with `window` would work in the standard browser case. Does anyone have an issue with detecting `window` and using it?

**Comment by ef4** [comment]
A quick search makes me think backburner might not need a reference to `window` at all.

But in general I think using window directly is fine, as long as you also handle the node case.

**Comment by stefanpenner** [comment]
You also need to handle the we worker case

**Comment by rwjblue** [comment]
I think that we can do:

```
var globalContext = typeof self !== 'undefined' ? self : global;
```

Should handle the normal browser context, the web worker context, and the node context.

**Comment by seanpdoyle** [comment]
@rwjblue where in the code would that go?

Here? https://github.com/ebryn/backburner.js/pull/129/files#diff-02b2bed86440a96ee1cbd07303beb61fR21

**Comment by rwjblue** [comment]
`lib/backburner/platform.js` in that branch is already doing the right thing (and guards better than my ternary above).

**Comment by seanpdoyle** [comment]
@rwjblue if that's the case, why is https://travis-ci.org/emberjs/ember.js/jobs/57735935#L164-L177 failing?

**Comment by rwjblue** [comment]
https://github.com/ebryn/backburner.js/blob/master/lib/backburner.umd.js#L8

**Comment by seanpdoyle** [comment]
@rwjblue would replacing

```js
} else if (typeof this !== 'undefined') {
```

with

```js
import platform from './platform';

// ...
} else if (typeof platform !== 'undefined') {
```

work?

**Comment by rwjblue** [comment]
yep, thats what I was thinking

**Comment by seanpdoyle** [comment]
@rwjblue resolved in https://github.com/ebryn/backburner.js/pull/134

**Comment by seanpdoyle** [comment]
@rwjblue applied this pattern to RSVP https://github.com/tildeio/rsvp.js/pull/380

**Comment by seanpdoyle** [comment]
@rwjblue also applied this pattern to dag-map https://github.com/krisselden/dag-map/pull/6
