### ISSUE TITLE
Scheduling a short setTimeout followed by a long one, causes the short one to hang until the long one executes

### ISSUE THREAD

**Issue by igorT** [ebryn/backburner.js#135]
Consider the case where we call `setTimeout(0)` and then `setTimeout(500)`
Currently if the `setTimeout(500)` is called in the same run loop as the first one, it will cause the `setTimeout(0)` to also wait 500 ms.

This bug was introduced by https://github.com/ebryn/backburner.js/pull/94

In particular, https://github.com/ebryn/backburner.js/pull/94/files#diff-820bd966639ebce8fcbffd97fb5dac41R441seems wrong, because if we have an expired timeout that hasn't fired, `wait` time should be `0`. 
I am a bit concerned with the computer sleep issue, because now and also with this fix, you could get  a timeout from couple days ago which is not how the native browser `setTimeout` behaves. Maybe we should have a max expired time after which we ignore the timeouted function?

This seems like a probable cause of https://github.com/emberjs/ember.js/issues/10479

**Comment by rbarbey** [comment]
I was experiencing issues because of this. The scheduled function

```javascript
Ember.run.later(this, function () {
  Ember.$('.panel').addClass('show');
}, 200);
```

was sometimes executed around 9-10 seconds after the the function was scheduled. With the changes that @igorT suggested my problem went away. So I took the liberty and fixed the problem as you can see from the pull request in #137
