### ISSUE TITLE
Clarification of dead code?

### ISSUE THREAD

**Issue by mariokostelac** [ebryn/backburner.js#156]
I've been looking at the `setTimeout` and I've found something that seems like a dead code.
Function `_reinstallStalledTimerTimeout ` https://github.com/ebryn/backburner.js/blob/master/lib/backburner.js#L603-L616 does seem like doing nothing. I do not see any returned value or modification of state that would affect rest of the system.

**Comment by stefanpenner** [comment]
timer related code has grown out of control, doesn't surprise me that some of it is just dangling.

It is in a big need of some TLC

**Comment by stefanpenner** [comment]
:)
