### ISSUE TITLE
get Name of currently executing queue

### ISSUE THREAD

**Issue by lindem** [ebryn/backburner.js#159]
Is there a straightforward way to see what queue a job has been scheduled to while the job is running (if, for example, the job contained a debugger statement)? IOW, can a job access the name of the queue it is running in?

**Comment by stefanpenner** [comment]
https://github.com/ebryn/backburner.js/blob/master/lib/backburner/queue.js#L158-L170 may be of interest also in that context `this.name` is available.

**Comment by lindem** [comment]
Thanks for the reply :-)
