### ISSUE TITLE
How to update an old Ember 1.12 app with new backburner

### ISSUE THREAD

**Issue by Leooo** [ebryn/backburner.js#168]
Hello. I have a problem quite systematic in my app of Ember.run.later loops not being run when the page is reloaded. Looking at github stackoverflow etc. I don't see anyone else complaining about it, so it seems to come from my app.

I'm using Ember 1.12, and on the last commit I have from https://github.com/components/ember/tree/1.12.2 the backburner version doesn't seem to be very recent, so my problem may be solved by updating backburner.

Now I don't understand how to update the backburner version on my app, as I don't have any reference to the backburner repo in the app on  https://github.com/components/ember/tree/1.12.2. If I look on https://github.com/emberjs/ember.js/tree/v1.12.2 then there is a ref to backburner in bower.json (commit is from nov 2014, quite old) but I don't seem to be able to build my ember from this source, as if I do so it tells me there is no ember-template-compiler.

Really stuck there and really need to update backburner. Could you explain if it is possible to do on an old Ember version (1.12.2) or if the backburner API changed and would not be compatible with the old Ember version, and if this is possible to update backburner how to do?

Thanks

**Comment by rwjblue** [comment]
This isn't something we support, however the steps you listed seem correct (bump in bower.json of emberjs/ember.js repo) and are what is done in Ember itself when updating back burner. 

I will note, that while the back burner used in 1.12 is old, so is 1.12 itself...

**Comment by Leooo** [comment]
Took me some time to understand that I had to rebuild myself the dist when using https://github.com/emberjs/ember.js/tree/v1.12.2, then save in vendor my own build etc. Enough time to realize that actually my original code had an issue. So no problem on backburner this time, sorry. Yes have to update to glimmer but still stuck with list-view for now until I upgrade to another addon thanks.
